#!/bin/sh

set -e

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$SNAP_USER_DATA/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$SNAP_USER_DATA/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$SNAP_USER_COMMON/.cache}"

mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME"

# Widevine CDM detection for DRM playback
CDM_NAME="libwidevinecdm.so"
for _wv_path in \
    "$SNAP_USER_DATA/$CDM_NAME" \
    "$SNAP_USER_COMMON/$CDM_NAME" \
    "$SNAP/extra/$CDM_NAME" \
    "$SNAP/opt/google/chrome/$CDM_NAME" \
    "$HOME/.local/share/netflix-client/widevine/$CDM_NAME" \
    "$HOME/.local/lib/$CDM_NAME"; do
    if [ -f "$_wv_path" ]; then
        export QTWEBENGINE_WIDEVINE_CDM_PATH="$_wv_path"
        break
    fi
done
unset _wv_path CDM_NAME

export QTWEBENGINE_DISABLE_SANDBOX="${QTWEBENGINE_DISABLE_SANDBOX:-1}"
export QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox --disable-setuid-sandbox --disable-gpu-sandbox --disable-gpu --enable-unsafe-swiftshader"

cd /
exec "$SNAP/bin/python3" -m app.main "$@"
