#!/bin/sh

set -e

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$SNAP_USER_DATA/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$SNAP_USER_DATA/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$SNAP_USER_COMMON/.cache}"

mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" "$XDG_CACHE_HOME"

# Widevine CDM detection for DRM playback
CDM_NAME="libwidevinecdm.so"
for _wv_dir in \
    "$SNAP_USER_DATA/data/widevine" \
    "$SNAP_USER_DATA/widevine" \
    "$SNAP_USER_COMMON/data/widevine" \
    "$SNAP_USER_COMMON/widevine" \
    "$SNAP/extra" \
    "$HOME/.config/google-chrome/WidevineCdm/_platform_specific/linux_x64" \
    "$HOME/.local/share/netflix-client/widevine" \
    "$HOME/.local/lib"; do
    if [ -f "$_wv_dir/$CDM_NAME" ]; then
        export QTWEBENGINE_WIDEVINE_CDM_PATH="$_wv_dir/$CDM_NAME"
        break
    fi
done
unset _wv_dir CDM_NAME

export QTWEBENGINE_DISABLE_SANDBOX="${QTWEBENGINE_DISABLE_SANDBOX:-1}"
export QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox --disable-setuid-sandbox --disable-gpu-sandbox --disable-gpu --enable-unsafe-swiftshader"

cd /
exec "$SNAP/bin/python3" -m app.main "$@"
